export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const GET_CONTRACT_LIST_SUCCESS = "GET_CONTRACT_LIST_SUCCESS";
export const GET_CONTRACT_LIST_FAIL = "GET_CONTRACT_LIST_FAIL";


export const GET_POINT_LIST_SUCCESS = "GET_POINT_LIST_SUCCESS";
export const GET_POINT_LIST_FAIL = "GET_POINT_LIST_FAIL";


export const ADD_POINT_SUCCESS = "ADD_POINT_SUCCESS";
export const ADD_POINT_FAIL = "ADD_POINT_FAIL";

export const GET_INVOICE_LIST_SUCCESS = "GET_INVOICE_LIST_SUCCESS";
export const GET_INVOICE_LIST_FAIL = "GET_INVOICE_LIST_FAIL";
